AllCops:
  TargetRubyVersion: 2.6
  Exclude:
    - 'test/**/*'
    - 'vendor/bundle/**/*'

Metrics:
  Enabled: false

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes
